engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  phpcodesniffer:
    enabled: true  
  phpmd:
    enabled: true


exclude_paths:
- "tests/*"
- "vendor/*"
- "app/storage/*"
