---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: docker build
  image: plugins/docker
  commands:
  - docker --version
  - docker ps
  - docker build .
