---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: docker build
  image: plugins/docker
  privileged: true
    environment:
      DOCKER_HOST: tcp://localhost:2375
  commands:
  - docker --version
  - docker build .
