---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: docker build
  image: plugins/docker
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  commands:
  - docker --version
  - docker build .
