---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: docker build
  image: plugins/docker
  priviledged: true
  commands:
  - docker --version
  - docker build .
