language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

before_install:
  - composer self-update

install: composer update --prefer-source -o

script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests

after_script:
  - ./vendor/bin/codacycoverage clover build/logs/clover.xml