language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

before_install:
  - composer self-update

install: composer update -o

script: ./vendor/bin/phpunit --coverage-clover _build/logs/clover.xml tests

after_script:
  - ./vendor/bin/codacycoverage clover _build/logs/clover.xml