language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n
  - php composer.phar update --dev

install:
  - composer install && composer update -o

script: ./vendor/bin/phpunit tests

after_script:
  - ./vendor/bin/test-reporter
  - ./vendor/bin/codacycoverage clover build/logs/clover.xml