language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar update -o

script: ./vendor/bin/phpunit tests

after_script:
  - ./vendor/bin/codacycoverage clover build/logs/clover.xml