language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly
  
notifications:
  slack: adrianpop:m8Fgi82QCbesEm354DhZ4i4t
  
cache:
  directories:
    - vendor

before_install:
  - composer self-update
  - rm -rf build
  - mkdir build

install: composer install && composer update -o

script: ./vendor/bin/phpunit --coverage-clover build/clover.xml tests

after_script:
  - ./vendor/bin/codacycoverage clover build/clover.xml